apiVersion: apps/v1
kind: Deployment
metadata:
  name: aaqib-app
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aaqib-app
  template:
    metadata:
      labels:
        app: aaqib-app
    spec:
      containers:
        - name: app-container
          image: nginx # replace with your app image
          envFrom:
            - secretRef:
                name: automatic-secret-created #--> This secret will created automatically by EXTERNAL-SECRET 
